name: .NET build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          7.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.2.1'

    - name: Restore & Build
      run: cmd /c "for /R %f in (*.sln) do dotnet restore "%f" | dotnet build "%f" /t:BatchBuild -m"