name: .NET build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          7.0.x
    
    - name: Build
      run: |
        Get-ChildItem . -Filter *.sln | Foreach-Object { 
          dotnet build $_.FullName /t:BatchBuild -v n
          if($SuccessCodes -notcontains $LastExitCode) {
            Exit $LastExitCode 
          } 
        }
